// Generated by https://quicktype.io

export interface ResponseI {
    total_count:        number;
    incomplete_results: boolean;
    items:              Item[];
}

export interface Item {
    url:                      string;
    repository_url:           string;
    labels_url:               string;
    comments_url:             string;
    events_url:               string;
    html_url:                 string;
    id:                       number;
    node_id:                  string;
    number:                   number;
    title:                    string;
    user:                     User;
    labels:                   Label[];
    state:                    string;
    locked:                   boolean;
    assignee:                 User | null;
    assignees:                User[];
    milestone:                Milestone | null;
    comments:                 number;
    created_at:               string;
    updated_at:               string;
    closed_at:                string;
    author_association:       AuthorAssociation;
    active_lock_reason:       null;
    body:                     string;
    reactions:                Reactions;
    timeline_url:             string;
    performed_via_github_app: null;
    state_reason:             string;
    score:                    number;
    draft?:                   boolean;
    pull_request?:            PullRequest;
}

export interface User {
    login:               string;
    id:                  number;
    node_id:             string;
    avatar_url:          string;
    gravatar_id:         string;
    url:                 string;
    html_url:            string;
    followers_url:       string;
    following_url:       string;
    gists_url:           string;
    starred_url:         string;
    subscriptions_url:   string;
    organizations_url:   string;
    repos_url:           string;
    events_url:          string;
    received_events_url: string;
    type:                Type;
    site_admin:          boolean;
}

export enum Type {
    User = "User",
}

export enum AuthorAssociation {
    Contributor = "CONTRIBUTOR",
    Member = "MEMBER",
    None = "NONE",
}

export interface Label {
    id:          number;
    node_id:     string;
    url:         string;
    name:        string;
    color:       Color;
    default:     boolean;
    description: string;
}

export enum Color {
    Bfd4F2 = "bfd4f2",
    D4C5F9 = "d4c5f9",
    Ededed = "ededed",
    F9Bda4 = "f9bda4",
    Fad8C7 = "fad8c7",
    The5319E7 = "5319e7",
}

export interface Milestone {
    url:           string;
    html_url:      string;
    labels_url:    string;
    id:            number;
    node_id:       string;
    number:        number;
    title:         string;
    description:   null | string;
    creator:       User;
    open_issues:   number;
    closed_issues: number;
    state:         string;
    created_at:    string;
    updated_at:    string;
    due_on:        null | string;
    closed_at:     string;
}



export interface PullRequest {
    url:       string;
    html_url:  string;
    diff_url:  string;
    patch_url: string;
    merged_at: null | string;
}

export interface Reactions {
    url:         string;
    total_count: number;
    "+1":        number;
    "-1":        number;
    laugh:       number;
    hooray:      number;
    confused:    number;
    heart:       number;
    rocket:      number;
    eyes:        number;
}
